spring:
  redis:
    host: 10.16.10.246
    port: 6379
    timeout: 3600
    password: NxmxRnBr1COZ
    database: 8
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0 # 连接池中的最小空闲连接
server:
  port: 8010
  context-path: /demo

zookeeper:
  hosts: 10.16.10.139:32768                         #zookeeper服务
  sessionTimeOutMs: 20000                           #会话超时时间，单位毫秒
  connectionTimeOutMs: 15000                        #连接超时时间，单位毫秒
  baseSleepTime: 1000                               #重试之间等待的初始时间，单位毫秒
  maxRetries: 5                                     #客户端连接最多重试次数
  lockPath: /root/test                              #锁根路径
  lockWaitTime: 30000                               #等待获取锁最长时间，单位毫秒

redisson:
  address: redis://${spring.redis.host}:${spring.redis.port}        # redis地址
  timeout: 3000                                                     # 超时时间
  connectionPoolSize: 64                                            # 连接池大小 默认64
  connectionMinimumIdleSize: 32                                     # 最小空闲连接数 默认32
